- hosts: testing
  remote_user: root

  tasks:
    - name: Instalar Rsyslog 
      apt: 
        name: rsyslog
        state: installed
        update_cache: true
      register: rsyslog_installed
      notify:
        - Start rsyslog

    - name: Arquivos de Configuracao
      copy:
        src: "{{ item }}"
        dest: /etc/rsyslog/
        owner: root
        group: root
        mode: 0644
      with_items:
        - /root/rsyslog.conf
      when: rsyslog_installed|success
      notify:
        - Restart rsyslog

  handlers:
    - name: Start rsyslog
      service: 
        name: rsyslog
        state: started
        
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted

