---
- hosts: node01
  tasks:
  - name: Instala servidor Memcached - Area de Testes da empresa Dexter
    yum: pkg=memcached state=installed update_cache=true
    register: memcached_installed
    notify:
    - Start Memcached

  - name: Define o arquivo de configuração do servidor Memcached - Área de Testes da empresa Dexter Courier
    when: memcached_installed|success
    copy: src=memcached.conf dest=/etc/memcached.conf owner=root group=root mode=0644
    notify:
    - Reload Memcached


  handlers:
  - name: Start Memcached
    service: 
     name: memcached
     state: started
        
  - name: Restart Memcached
    service:
      name: memcached
      state: restarted