---
- name: Define os arquivos de configuracao do servidor DNS
  when: bind_installed|success
  copy: src={{item}} dest=/etc/bind/ owner=root group=root mode=0644
  with_items:
    - named.conf.local
    - named.conf.options
  notify:
    - Reload Bind